/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e3.convertidorn;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jnapo
 */
public class Convertidor extends javax.swing.JFrame {
    
    public Convertidor() {
        initComponents();
        setTitle("Convertidor");
        setLocationRelativeTo(null);
        setResizable(false);
    }

    Cadena cad=new Cadena();
    Funciones f=new Funciones();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField0 = new javax.swing.JTextField();
        btnCalc = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Secuencia:");

        jTextField1.setFocusable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Frase:");

        jTextField0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField0ActionPerformed(evt);
            }
        });

        btnCalc.setText("Calcular");
        btnCalc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });

        btnHistorial.setText("Historial");
        btnHistorial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCalc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField0, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField0, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(btnCalc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField0ActionPerformed

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        
        cad.setCadena(jTextField0.getText().toUpperCase());
        for(int i=0; i<jTextField0.getText().length();i++){
            
            
            if(cad.getCadena().charAt(i)=='A'){
                System.out.println("2");
                cad.setSecuenciaF(cad.getSecuenciaF()+"2 ");
            }
            if(cad.getCadena().charAt(i)=='B'){
                System.out.println("22");
                cad.setSecuenciaF(cad.getSecuenciaF()+"22 ");
            }
            if(cad.getCadena().charAt(i)=='C'){
                System.out.println("222");
                cad.setSecuenciaF(cad.getSecuenciaF()+"222 ");
            }
            if(cad.getCadena().charAt(i)=='D'){
                System.out.println("3");
                cad.setSecuenciaF(cad.getSecuenciaF()+"3 ");
            }
            if(cad.getCadena().charAt(i)=='E'){
                System.out.println("33");
                cad.setSecuenciaF(cad.getSecuenciaF()+"33 ");
            }
            if(cad.getCadena().charAt(i)=='F'){
                System.out.println("333");
                cad.setSecuenciaF(cad.getSecuenciaF()+"333 ");
            }
            if(cad.getCadena().charAt(i)=='G'){
                System.out.println("4");
                cad.setSecuenciaF(cad.getSecuenciaF()+"4 ");
            }
            if(cad.getCadena().charAt(i)=='H'){
                System.out.println("44");    
                cad.setSecuenciaF(cad.getSecuenciaF()+"44 ");
            }
            if(cad.getCadena().charAt(i)=='I'){
                System.out.println("444");
                cad.setSecuenciaF(cad.getSecuenciaF()+"444 ");
            }
            if(cad.getCadena().charAt(i)=='J'){
                System.out.println("5");
                cad.setSecuenciaF(cad.getSecuenciaF()+"5 ");
            }
            if(cad.getCadena().charAt(i)=='K'){
                System.out.println("55");
                cad.setSecuenciaF(cad.getSecuenciaF()+"55 ");
            }
            if(cad.getCadena().charAt(i)=='L'){
                System.out.println("555");
                cad.setSecuenciaF(cad.getSecuenciaF()+"555 ");
            }
            if(cad.getCadena().charAt(i)=='M'){
                System.out.println("6");
                cad.setSecuenciaF(cad.getSecuenciaF()+"6 ");
            }
            if(cad.getCadena().charAt(i)=='N'){
                System.out.println("66");
                cad.setSecuenciaF(cad.getSecuenciaF()+"66 ");
            }
            if(cad.getCadena().charAt(i)=='O'){
                System.out.println("666");
                cad.setSecuenciaF(cad.getSecuenciaF()+"666 ");
            }
            if(cad.getCadena().charAt(i)=='P'){
                System.out.println("7");
                cad.setSecuenciaF(cad.getSecuenciaF()+"7 ");
            }
            if(cad.getCadena().charAt(i)=='Q'){
                System.out.println("77");
                cad.setSecuenciaF(cad.getSecuenciaF()+"77 ");
            }
            if(cad.getCadena().charAt(i)=='R'){
                System.out.println("777");
                cad.setSecuenciaF(cad.getSecuenciaF()+"777 ");
            }
            if(cad.getCadena().charAt(i)=='S'){
                System.out.println("7777");
                cad.setSecuenciaF(cad.getSecuenciaF()+"7777 ");
            }
            if(cad.getCadena().charAt(i)=='T'){
                System.out.println("8");
                cad.setSecuenciaF(cad.getSecuenciaF()+"8 ");
            }
            if(cad.getCadena().charAt(i)=='U'){
                System.out.println("88");
                cad.setSecuenciaF(cad.getSecuenciaF()+"88 ");
            }
            if(cad.getCadena().charAt(i)=='V'){
                System.out.println("888");
                cad.setSecuenciaF(cad.getSecuenciaF()+"888 ");
            }
            if(cad.getCadena().charAt(i)=='W'){
                System.out.println("9");
                cad.setSecuenciaF(cad.getSecuenciaF()+"9 ");
            }
            if(cad.getCadena().charAt(i)=='X'){
                System.out.println("99");
                cad.setSecuenciaF(cad.getSecuenciaF()+"99 ");
            }
            if(cad.getCadena().charAt(i)=='Y'){
                System.out.println("999");
                cad.setSecuenciaF(cad.getSecuenciaF()+"999 ");
            }
            if(cad.getCadena().charAt(i)=='Z'){
                System.out.println("9999");
                cad.setSecuenciaF(cad.getSecuenciaF()+"9999 ");
            }
            if(cad.getCadena().charAt(i)=='0'){
                System.out.println("00");
                cad.setSecuenciaF(cad.getSecuenciaF()+"00 ");
            }
            if(cad.getCadena().charAt(i)=='1'){
                System.out.println("1");
                cad.setSecuenciaF(cad.getSecuenciaF()+"1 ");
            }
            if(cad.getCadena().charAt(i)=='2'){
                System.out.println("2222");
                cad.setSecuenciaF(cad.getSecuenciaF()+"2222 ");
            }
            if(cad.getCadena().charAt(i)=='3'){
                System.out.println("3333");
                cad.setSecuenciaF(cad.getSecuenciaF()+"3333 ");
            }
            if(cad.getCadena().charAt(i)=='4'){
                System.out.println("4444");
                cad.setSecuenciaF(cad.getSecuenciaF()+"4444 ");
            }
            if(cad.getCadena().charAt(i)=='5'){
                System.out.println("5555");
                cad.setSecuenciaF(cad.getSecuenciaF()+"5555 ");
            }
            if(cad.getCadena().charAt(i)=='6'){
                System.out.println("6666");
                cad.setSecuenciaF(cad.getSecuenciaF()+"6666 ");
            }
            if(cad.getCadena().charAt(i)=='7'){
                System.out.println("77777");
                cad.setSecuenciaF(cad.getSecuenciaF()+"77777 ");
            }
            if(cad.getCadena().charAt(i)=='8'){
                System.out.println("8888");
                cad.setSecuenciaF(cad.getSecuenciaF()+"8888");
            }
            if(cad.getCadena().charAt(i)=='9'){
                System.out.println("99999");
                cad.setSecuenciaF(cad.getSecuenciaF()+"99999 ");
            }
            if(cad.getCadena().charAt(i)==' '){
                System.out.println("0");
                cad.setSecuenciaF(cad.getSecuenciaF()+"0 ");
            }
            if(cad.getCadena().charAt(i)=='Ñ'){
                JOptionPane.showMessageDialog(null,"No se admiten «Ñ»");
                break;
            }
            
        cad.setSecuenciaF(cad.getSecuenciaF().replaceAll("n",""));  
        cad.setSecuenciaF(cad.getSecuenciaF().replaceAll("u","")); 
        cad.setSecuenciaF(cad.getSecuenciaF().replaceAll("l","")); 
        
        }
        
        
            jTextField1.setText(cad.getSecuenciaF());

         if(jTextField0.getText().isEmpty()){

             JOptionPane.showMessageDialog(null,"Ingresa un texto");
         }else{
             try {
             f.agregar(jTextField0.getText(),jTextField1.getText());
         } catch (IOException ex) {
             Logger.getLogger(Convertidor.class.getName()).log(Level.SEVERE, null, ex);
         }
         } 
        
        
        cad.setCadena("");
        cad.setSecuenciaF("");
    }//GEN-LAST:event_btnCalcActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        
        try {
            f.Leer();
        } catch (IOException ex) {
            Logger.getLogger(Convertidor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Convertidor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        jTextField0.setText("");
        
        jTextField1.setText("");
    }//GEN-LAST:event_btnBorrarActionPerformed
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Convertidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCalc;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField0;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
